version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: arithmetic-calculator
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - /mysql/db/data:/var/lib/mysql
    ports:
      - "3306:3306"
